test_that("search and tau defaults preserve the frozen donor values", {
  expect_identical(QUADRATIC_PROFILE_CONTROL, list(
    CONSTRAINT_SCALE_FLOOR_RTOL = 1e-12, SYMMETRY_RTOL = 1e-8,
    SOLVER_BOXES = c(1e6, 1e9, 1e10), SOLVER_XTOL_REL = 1e-8,
    SOLVER_MAXEVAL = 1000L, FEASIBILITY_TOLERANCE = 1e-4,
    ADMISSION_TOLERANCE = 1e-10, CANDIDATE_CORRECTION_RTOL = 1e-6,
    BOUND_EDGE_RTOL = 0.99, BOUND_STABILITY_RTOL = 1e-3,
    MULTISTART_ROUNDS = 4L, MULTISTART_DEDUP_DIGITS = 6L
  ))
  expect_identical(MEAN_TAU_CONTROL, list(
    CAP = 0.99, SWEEP_STEP = 0.005, BISECTION_ITERATIONS = 40L
  ))
})
