# Numbers quoted in the paper for the SDF approximation errors: the paragraph
# following the approximation equations in draft.tex and the bottom-line
# sentences of the Internet Appendix's Empirical Bound subsubsection.
#
# Standalone by design: run with `Rscript quoted_numbers.R` from this folder
# (or source it from anywhere). It is not sourced by run_pipeline.R and is not
# in the artifact manifest; it reproduces the pipeline's quarterly ACM inputs
# directly through the package so the quoted numbers can be regenerated and
# checked without running the full pipeline. Writes to output/quoted_numbers.

library(hetid)

step_qtr <- 3L
mats_all <- HETID_CONSTANTS$ALL_ACM_MATURITIES
acm <- suppressWarnings(extract_acm_data(
  data_types = c("yields", "term_premia"),
  maturities = mats_all,
  frequency = "quarterly"
))
yields <- acm[, acm_column_name("yields", mats_all)]
term_premia <- acm[, acm_column_name("term_premia", mats_all)]
sample_txt <- sprintf(
  "quarterly, %s to %s, T = %d observations",
  format(min(as.Date(acm$date)), "%Y-%m"), format(max(as.Date(acm$date)), "%Y-%m"),
  nrow(acm)
)

# reported per-maturity bounds: for each error the smaller of the fourth-order
# plug-in and the no-Taylor-expansion plug-in, on the quarterly grid
vb_mats <- seq(step_qtr, effective_max_maturity(step_qtr), by = step_qtr)
ub_news <- pmin(
  vapply(vb_mats, \(i) compute_variance_bound(yields, term_premia, i = i, step = step_qtr), numeric(1)),
  vapply(vb_mats, \(i) compute_news_q_bound(yields, term_premia, i = i, step = step_qtr), numeric(1))
)
ub_expected <- vapply(
  vb_mats,
  \(i) compute_expected_sdf_variance_bound(yields, term_premia, i = i, step = step_qtr),
  numeric(1)
)
stopifnot(
  "bounds must be finite and positive" =
    all(is.finite(ub_news)) && all(is.finite(ub_expected)) &&
      all(ub_news > 0) && all(ub_expected > 0)
)

# error standard-deviation bounds in basis points of the SDF level (1 bp = 1e-4)
sd_bp_news <- 1e4 * sqrt(ub_news)
sd_bp_expected <- 1e4 * sqrt(ub_expected)

# typical quarterly movement in the one-quarter yield: the sample standard
# deviation of the quarterly changes of the one-quarter (step-month) yield, in
# per-quarter decimal units (annualized percent divided by 400)
y1_qtr_decimal <- yields[[acm_column_name("yields", step_qtr)]] / 400
typical_move <- stats::sd(diff(y1_qtr_decimal), na.rm = TRUE)

quoted <- data.frame(
  name = c(
    "max_bound_sdf_news",
    "max_bound_expected_sdf",
    "max_error_sd_bp",
    "typical_quarterly_move_one_quarter_yield",
    "max_error_sd_over_typical_move_pct"
  ),
  value = c(
    max(ub_news),
    max(ub_expected),
    max(sd_bp_news, sd_bp_expected),
    typical_move,
    100 * max(sqrt(ub_news), sqrt(ub_expected)) / typical_move
  )
)

# the claims as quoted in the paper; fail loud if a regeneration breaks one
stopifnot(
  "draft quotes max news bound 4.19e-9" =
    abs(max(ub_news) - 4.19e-9) < 5e-12,
  "draft quotes max expected bound 3.19e-9" =
    abs(max(ub_expected) - 3.19e-9) < 5e-12,
  "error sd below 0.7 bp at every maturity" =
    max(sd_bp_news, sd_bp_expected) < 0.7,
  "error sd below 3 percent of a typical quarterly yield move" =
    quoted$value[quoted$name == "max_error_sd_over_typical_move_pct"] < 3
)

out_dir <- file.path(dirname(dirname(getwd())), "scripts-paper", "output", "quoted_numbers")
if (!dir.exists(out_dir)) {
  out_dir <- file.path("..", "output", "quoted_numbers")
}
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

write.csv(quoted, file.path(out_dir, "approximation_error_quoted_numbers.csv"),
  row.names = FALSE
)

desc <- c(
  "# Numbers quoted for the SDF approximation errors",
  "",
  sprintf(
    "Generated by scripts-paper/variance_bounds/quoted_numbers.R. Sample: %s",
    sample_txt
  ),
  "(the full quarterly ACM zero-coupon yields and term premia, sampled at",
  "quarter ends, annualized percent divided by 400 inside the estimators).",
  "",
  "Quoted in the main-text paragraph after the approximation equations and in",
  "the Internet Appendix's Empirical Bound subsubsection and Table/Figure on",
  "the variance bounds.",
  "",
  sprintf("- max_bound_sdf_news = %.3e.", max(ub_news)),
  "  Largest, over the 39 quarterly maturities i = 3, 6, ..., 117 months, of",
  "  the reported SDF-news variance bound: at each maturity the smaller of the",
  "  fourth-order plug-in (1/4) c_hat (k_hat + k2_hat), from",
  "  compute_variance_bound(), and the no-Taylor-expansion plug-in",
  "  (sd(w_hat) + sd(q_hat) + sd(z_hat))^2, from compute_news_q_bound().",
  sprintf(
    "  The no-Taylor bound is the smaller one only at the shortest maturity; the maximum is attained at %d months.",
    vb_mats[which.max(ub_news)]
  ),
  "",
  sprintf("- max_bound_expected_sdf = %.3e.", max(ub_expected)),
  "  Same construction for the expected-SDF error: the smaller of the",
  "  fourth-order plug-in (1/4) c_hat j_hat and the variance of the",
  "  first-order-cancelled gap, from compute_expected_sdf_variance_bound().",
  sprintf("  The maximum is attained at %d months.", vb_mats[which.max(ub_expected)]),
  "",
  sprintf(
    "- max_error_sd_bp = %.3f basis points (quoted as 'below 0.7 basis points').",
    max(sd_bp_news, sd_bp_expected)
  ),
  "  Square root of the larger of the two bounds at each maturity, times 1e4:",
  "  the approximation errors are in levels of the SDF, so 1e-4 of the level",
  "  is one basis point.",
  "",
  sprintf(
    "- typical_quarterly_move_one_quarter_yield = %.5f (per-quarter decimal).",
    typical_move
  ),
  "  Sample standard deviation of the quarterly first differences of the",
  "  one-quarter yield (the 3-month ACM yield divided by 400).",
  "",
  sprintf(
    "- max_error_sd_over_typical_move_pct = %.2f percent (quoted as 'less than 3 percent').",
    quoted$value[quoted$name == "max_error_sd_over_typical_move_pct"]
  ),
  "  Largest error-standard-deviation bound across maturities and both",
  "  approximations, divided by the typical quarterly move above. The",
  "  comparison uses that a one-quarter-yield move of dy moves the one-period",
  "  bond price, and hence the SDF level, by approximately dy times a price",
  "  close to one.",
  "",
  "All bounds are plug-in estimates of population bounds, not finite-sample",
  "guarantees; see the Internet Appendix's Empirical Bound subsubsection."
)
writeLines(desc, file.path(out_dir, "approximation_error_quoted_numbers.md"))

cat("wrote", out_dir, "\n")
print(quoted, digits = 4)
