# Pure builders for the paper's quoted SDF approximation-error numbers: the
# five-row name/value frame and the markdown note derived from it. Sourced by
# the pipeline driver and by the contract test; no side effects on source.

VARIANCE_BOUNDS_QUOTED_NAMES <- c(
  "max_bound_sdf_news",
  "max_bound_expected_sdf",
  "max_error_sd_bp",
  "typical_quarterly_move_one_quarter_yield",
  "max_error_sd_over_typical_move_pct"
)

.quoted_bound_columns <- c(
  "Maturity", "Variance_Bound", "Expected_SDF_Bound",
  "News_Envelope_Bound", "News_Q_Bound"
)

variance_bounds_quoted_check_frame <- function(bounds_df) {
  stopifnot(
    "bounds frame must carry the reported and arm bound columns" =
      is.data.frame(bounds_df) && nrow(bounds_df) >= 3L &&
        all(.quoted_bound_columns %in% names(bounds_df)),
    "bound columns must all be numeric" =
      all(vapply(bounds_df[.quoted_bound_columns], is.numeric, logical(1))),
    "maturities must be >= 3 positive whole months on a constant step" =
      all(is.finite(bounds_df$Maturity)) && bounds_df$Maturity[1L] >= 1 &&
        all(bounds_df$Maturity == round(bounds_df$Maturity)) &&
        length(unique(diff(bounds_df$Maturity))) == 1L &&
        diff(bounds_df$Maturity)[1L] > 0,
    "reported news bound must equal the pointwise minimum of its two arms" =
      identical(
        bounds_df$Variance_Bound,
        pmin(bounds_df$News_Envelope_Bound, bounds_df$News_Q_Bound)
      ),
    "reported bounds must be finite and positive" =
      all(is.finite(bounds_df$Variance_Bound) & bounds_df$Variance_Bound > 0) &&
        all(is.finite(bounds_df$Expected_SDF_Bound) &
          bounds_df$Expected_SDF_Bound > 0),
    "news arm bounds must be positive and non-NA (Inf allowed for the q arm)" =
      all(is.finite(bounds_df$News_Envelope_Bound) &
        bounds_df$News_Envelope_Bound > 0) &&
        all(!is.na(bounds_df$News_Q_Bound) & bounds_df$News_Q_Bound > 0)
  )
  invisible(bounds_df)
}

variance_bounds_quoted_numbers <- function(bounds_df, y1q_yield) {
  variance_bounds_quoted_check_frame(bounds_df)
  stopifnot(
    "one-quarter yield must be numeric, NA-free, length >= 3" =
      is.numeric(y1q_yield) && length(y1q_yield) >= 3L && !anyNA(y1q_yield)
  )
  typical_move <- stats::sd(diff(y1q_yield))
  stopifnot(
    "typical quarterly move must be finite and positive" =
      is.finite(typical_move) && typical_move > 0
  )
  max_sd <- max(
    sqrt(bounds_df$Variance_Bound),
    sqrt(bounds_df$Expected_SDF_Bound)
  )
  data.frame(
    name = VARIANCE_BOUNDS_QUOTED_NAMES,
    value = c(
      max(bounds_df$Variance_Bound),
      max(bounds_df$Expected_SDF_Bound),
      1e4 * max_sd,
      typical_move,
      100 * max_sd / typical_move
    )
  )
}

variance_bounds_quoted_md_lines <- function(quoted, bounds_df, sample_txt) {
  variance_bounds_quoted_check_frame(bounds_df)
  stopifnot(
    "quoted frame must carry the five canonical rows in order" =
      is.data.frame(quoted) &&
        identical(quoted$name, VARIANCE_BOUNDS_QUOTED_NAMES) &&
        is.numeric(quoted$value) && length(quoted$value) == 5L &&
        all(is.finite(quoted$value) & quoted$value > 0),
    "sample description must be one nonempty string" =
      is.character(sample_txt) && length(sample_txt) == 1L &&
        nzchar(sample_txt),
    "quoted maxima must come from this bounds frame" =
      identical(quoted$value[[1L]], max(bounds_df$Variance_Bound)) &&
        identical(quoted$value[[2L]], max(bounds_df$Expected_SDF_Bound))
  )
  v <- stats::setNames(quoted$value, quoted$name)
  mats <- bounds_df$Maturity
  q_binding <- mats[bounds_df$News_Q_Bound < bounds_df$News_Envelope_Bound]
  argmax_news <- mats[which.max(bounds_df$Variance_Bound)]
  binding_lines <- if (length(q_binding)) {
    c(
      sprintf(
        "  The no-Taylor q-arm is the smaller one at %d of the %d maturities",
        length(q_binding), nrow(bounds_df)
      ),
      sprintf(
        "  (months: %s); the maximum is attained at %d months.",
        paste(q_binding, collapse = ", "), argmax_news
      )
    )
  } else {
    c(
      sprintf(
        "  The no-Taylor q-arm is the smaller one at none of the %d maturities",
        nrow(bounds_df)
      ),
      sprintf("  ; the maximum is attained at %d months.", argmax_news)
    )
  }
  c(
    "# Numbers quoted for the SDF approximation errors",
    "",
    sprintf(
      "Generated by scripts-paper/variance_bounds/quoted/run.R. Sample: %s",
      sample_txt
    ),
    "(the full quarterly ACM zero-coupon yields and term premia; each quarter",
    "carries its last available monthly observation, relabeled to the calendar",
    "quarter end, so the final quarter may be incomplete and is included per",
    "the pinned use_incomplete_quarters = TRUE policy; the typical-move",
    "statistic below uses one fewer observation than T, its first difference).",
    "",
    "Quoted in the main-text paragraph after the approximation equations and in",
    "the Internet Appendix's Empirical Bound subsubsection and Table/Figure on",
    "the variance bounds.",
    "",
    sprintf("- max_bound_sdf_news = %.3e.", v[["max_bound_sdf_news"]]),
    sprintf(
      "  Largest, over the %d quarterly maturities i = %d, %d, ..., %d months,",
      nrow(bounds_df), mats[1L], mats[2L], mats[length(mats)]
    ),
    "  of the reported SDF-news variance bound: at each maturity the smaller",
    "  of the fourth-order envelope plug-in (1/4) c_hat (k_hat + k2_hat), from",
    "  compute_variance_bound(), and the first-order-cancelled plug-in",
    "  (sigma_hat(q1_hat) + sigma_hat(q0_hat) + sigma_hat(g_hat))^2, from",
    "  compute_news_q_bound().",
    binding_lines,
    "",
    sprintf(
      "- max_bound_expected_sdf = %.3e.", v[["max_bound_expected_sdf"]]
    ),
    "  Same construction for the expected-SDF error: the reported bound is",
    "  min{(1/4) C_hat K_hat, Var_hat(q)}, the fourth-order plug-in against",
    "  the first-order-cancelled q-bound, from",
    "  compute_expected_sdf_variance_bound().",
    sprintf(
      "  The maximum is attained at %d months.",
      mats[which.max(bounds_df$Expected_SDF_Bound)]
    ),
    "",
    sprintf(
      "- max_error_sd_bp = %.3f basis points (quoted as 'below 0.7 basis points').",
      v[["max_error_sd_bp"]]
    ),
    "  Square root of the larger of the two bounds at each maturity, times 1e4:",
    "  the approximation errors are in levels of the SDF, so 1e-4 of the level",
    "  is one basis point.",
    "",
    sprintf(
      "- typical_quarterly_move_one_quarter_yield = %.5f (per-quarter decimal).",
      v[["typical_quarterly_move_one_quarter_yield"]]
    ),
    "  Sample standard deviation of the quarterly first differences of the",
    "  one-quarter yield (the 3-month ACM yield, annualized percent divided",
    "  by 400 to a per-quarter decimal).",
    "",
    sprintf(
      "- max_error_sd_over_typical_move_pct = %.2f percent (quoted as 'less than 3 percent').",
      v[["max_error_sd_over_typical_move_pct"]]
    ),
    "  Largest error-standard-deviation bound across maturities and both",
    "  approximations, divided by the typical quarterly move above. The",
    "  comparison uses that a one-quarter-yield move of dy moves the one-period",
    "  bond price, and hence the SDF level, by approximately dy times a price",
    "  close to one.",
    "",
    "All bounds are plug-in estimates of population bounds, not finite-sample",
    "guarantees; see the Internet Appendix's Empirical Bound subsubsection."
  )
}
