#' Log-Variance Estimator Registry and Design Builder
#'
#' The registry maps estimator names to fitting workers, covariance workers,
#' and supported standard-error types. Callers resolve an estimator string
#' through \code{\link{log_variance_estimator}}.
#'
#' @name log_variance_estimator_registry
#' @keywords internal
NULL

#' Supported Log-Variance Estimator Specs
#'
#' Built inside a function, not stored as a package-level constant: the
#' \code{fit_response} slot points at a worker defined in a later-sourced
#' file, which would not exist yet at build time.
#'
#' @noRd
log_variance_estimator_specs <- function() {
  list(
    ppml = list(
      id = "ppml",
      label = "PPML (quasi-Poisson, log link)",
      fit_response = ppml_fit_response,
      vcov = ppml_vcov_variants,
      se_types = LOG_VARIANCE_CONTROL$SE_TYPES
    ),
    harvey = list(
      id = "harvey",
      label = "Harvey (Gaussian multiplicative heteroskedasticity)",
      fit_response = harvey_fit_response,
      vcov = harvey_vcov_variants,
      se_types = LOG_VARIANCE_HARVEY_CONTROL$SE_TYPES
    )
  )
}

#' Look Up a Log-Variance Estimator Spec
#'
#' Resolves a registered estimator name to its workers and standard-error types.
#' Invalid names signal a \code{hetid_error_bad_argument} condition.
#'
#' @param estimator Single string naming the estimator (\code{"ppml"} or
#'   \code{"harvey"}). Missing values are not allowed.
#'
#' @return A named list with character scalars \code{id} and \code{label},
#'   functions \code{fit_response} and \code{vcov}, and a character vector
#'   \code{se_types} of supported standard-error types.
#' @keywords internal
log_variance_estimator <- function(estimator) {
  specs <- log_variance_estimator_specs()
  valid <- names(specs)
  assert_bad_argument_ok(
    is.character(estimator) && length(estimator) == 1L &&
      !is.na(estimator) && estimator %in% valid,
    paste0("estimator must be one of: ", paste(valid, collapse = ", ")),
    arg = "estimator"
  )
  specs[[estimator]]
}

#' Build the Log-Variance Design Matrix
#'
#' Prepends the intercept column to the volatility regressors. Column labels
#' are validated on the \emph{final} design, so an \code{x} column already
#' named \code{"(Intercept)"} is a collision and errors: duplicate or blank
#' labels would later corrupt coefficient identity and the SE frame.
#'
#' @details
#' Missing and non-finite regressor values are preserved; this helper does not
#' remove rows or check regressor finiteness. Invalid column labels or a
#' nonnumeric design signal a \code{hetid_error_bad_argument} condition.
#'
#' @param x Numeric matrix (or object coercible by
#'   \code{\link[base]{as.matrix}}) of volatility regressors, without an
#'   intercept column. When column names are absent, they are generated by
#'   \code{\link{get_pc_column_names}}.
#'
#' @return A numeric matrix with the same rows as \code{as.matrix(x)} and
#'   one additional column. The first column contains ones and is named
#'   \code{"(Intercept)"}; all column labels are unique, non-missing, and
#'   non-blank. A zero-column input produces an intercept-only matrix.
#' @keywords internal
log_variance_design <- function(x) {
  x <- as.matrix(x)
  if (is.null(colnames(x))) {
    colnames(x) <- get_pc_column_names(ncol(x))
  }
  design <- cbind(rep(1, nrow(x)), x)
  colnames(design) <- c(HETID_CONSTANTS$INTERCEPT_LABEL, colnames(x))
  design_labels <- colnames(design)
  assert_bad_argument_ok(
    is.numeric(design) && !anyNA(design_labels) &&
      all(nzchar(design_labels)) && !anyDuplicated(design_labels),
    paste0(
      "design column labels must be non-missing, non-blank, and unique ",
      "(the intercept column is named ", HETID_CONSTANTS$INTERCEPT_LABEL, ")"
    ),
    arg = "x"
  )
  design
}

#' Classify the Scaled Response
#'
#' Guards the one place where \code{response_scale} can quietly change the
#' data an estimator sees. Partial underflow is the sneaky case: zeros are
#' otherwise valid responses, so a positive entry collapsing to exactly zero
#' looks like data rather than a numerical accident. Shared by every
#' estimator's \code{fit_response} worker.
#'
#' @details
#' Callers validate the original response and positive finite scale before
#' calling this helper. It does not validate vector lengths or remove missing
#' values.
#'
#' @param y Finite nonnegative numeric response vector on the original scale.
#' @param y_scaled Numeric vector of the same length as \code{y}, obtained
#'   as \code{y / response_scale}.
#'
#' @return A character scalar: \code{"scaled_response_underflow"} if a
#'   positive original response becomes exactly zero,
#'   \code{"scaled_response_overflow"} if the scaled response is non-finite,
#'   or \code{"all_zero_response"} if it has no positive entries. Checks
#'   occur in that order. Returns \code{NA_character_} when none applies.
#' @keywords internal
log_variance_scaled_response_class <- function(y, y_scaled) {
  if (any(y > 0 & y_scaled == 0)) {
    return("scaled_response_underflow")
  }
  if (!all(is.finite(y_scaled))) {
    return("scaled_response_overflow")
  }
  # An all-zero response leaves PPML's rank check with no rows for svd()
  if (!any(y_scaled > 0)) {
    return("all_zero_response")
  }
  NA_character_
}
