#' Recover Structural First-Stage Coefficients of the Y1 Equation
#'
#' Maps a value (or a set of values) of the structural parameter
#' \eqn{\boldsymbol{\theta}} to the structural first-stage coefficient vector
#' \eqn{\boldsymbol{\beta}_1(\boldsymbol{\theta})} of the consumption-growth
#' equation, via the exact affine identity
#' \deqn{\boldsymbol{\beta}_1(\boldsymbol{\theta}) = \boldsymbol{\beta}_1^{R}
#'   - (\boldsymbol{\beta}_2^{R})^{\top}\boldsymbol{\theta}.}
#'
#' @param beta1r Named numeric vector of length \eqn{p}: the OLS coefficients of
#'   \eqn{Y_1} on the common conditioning vector \eqn{X = (1, PC', \text{own-lags})},
#'   i.e. the \code{coefficients} element of \code{\link{compute_w1_residuals}}.
#'   Names are \code{c("(Intercept)", "pc1", ..., "l.y1", ...)}; with no lags
#'   \eqn{p = 1 + n\_pcs}.
#' @param beta2r Numeric \eqn{I \times p} matrix: the OLS coefficients of the
#'   \eqn{I} components of \eqn{Y_2} on the same \eqn{X}, i.e. the
#'   \code{coefficients} element of \code{\link{compute_w2_residuals}}. Row
#'   \eqn{i} is \eqn{(\alpha_{i0}, \alpha_{i1}, \ldots)}. This matrix \emph{is}
#'   the point-identified \eqn{\boldsymbol{\beta}_{20}} (the \eqn{Y_2}-equation
#'   coefficient matrix), which is identified independently of
#'   \eqn{\boldsymbol{\theta}}. Its column names must match \code{names(beta1r)}.
#' @param theta Either a numeric vector of length \eqn{I} (a single point) or a
#'   numeric \eqn{I \times K} matrix whose columns are \eqn{K} candidate
#'   \eqn{\boldsymbol{\theta}} vectors (e.g. vertices of the identified set).
#'   The \eqn{\boldsymbol{\theta}} axis is matched to the \emph{rows} of
#'   \code{beta2r} \strong{by position, not by name}: the row labels of
#'   \code{beta2r} (bond maturities) and the entries of \code{theta} (system
#'   components) are intentionally labelled differently, so the caller must
#'   supply them in the same order.
#'
#' @return For a vector \code{theta}, a named numeric vector of length \eqn{p}.
#'   For a matrix \code{theta}, a \eqn{p \times K} numeric matrix with row names
#'   carried from \code{names(beta1r)} and column names from
#'   \code{colnames(theta)}.
#'
#' @details
#' The population map
#' \eqn{\boldsymbol{\beta}_1(\boldsymbol{\theta}) = (E[XX'])^{-1}
#'   E[X(Y_1 - \boldsymbol{\theta}'Y_2)]} collapses exactly to the affine form
#' above, because \eqn{(E[XX'])^{-1}E[XY_1] = \boldsymbol{\beta}_1^{R}} and
#' \eqn{(E[XX'])^{-1}E[XY_2'] = (\boldsymbol{\beta}_2^{R})^{\top}}. The
#' constant, principal-component, and own-lag coefficients therefore vary affinely with
#' \eqn{\boldsymbol{\theta}}, while \eqn{\boldsymbol{\beta}_{20} =
#' \boldsymbol{\beta}_2^{R}} does not depend on \eqn{\boldsymbol{\theta}}.
#'
#' @section Sample consistency:
#' The identity is exact at the sample level \emph{only} when \code{beta1r} and
#' \code{beta2r} are OLS fits on the identical design matrix \eqn{X} and the
#' identical set of rows. Supply coefficients produced from a single aligned
#' sample (the residuals feeding the identified set are generated by exactly
#' these coefficients); fitting \eqn{Y_1} and \eqn{Y_2} on different retained
#' rows makes the returned value only asymptotically, not numerically, equal to
#' a direct OLS of \eqn{Y_1 - \boldsymbol{\theta}'Y_2} on \eqn{X}.
#'
#' @seealso \code{\link{compute_w1_residuals}}, \code{\link{compute_w2_residuals}}
#'
#' @export
#'
#' @examples
#' set.seed(42)
#' n <- 200
#' x <- cbind(1, matrix(rnorm(n * 2), n, 2))
#' colnames(x) <- c("(Intercept)", "pc1", "pc2")
#' beta1r <- stats::setNames(c(0.5, -0.2, 0.1), colnames(x))
#' beta2r <- matrix(rnorm(2 * 3),
#'   nrow = 2, ncol = 3,
#'   dimnames = list(c("maturity_24", "maturity_60"), colnames(x))
#' )
#' theta <- c(0.3, -0.4)
#' recover_structural_coefficients(beta1r, beta2r, theta)
#'
#' # Batch over candidate theta vectors (columns of a matrix)
#' theta_set <- cbind(c(0, 0), c(0.3, -0.4), c(1, 1))
#' recover_structural_coefficients(beta1r, beta2r, theta_set)
recover_structural_coefficients <- function(beta1r, beta2r, theta) {
  assert_bad_argument_ok(
    is.numeric(beta1r) && is.null(dim(beta1r)),
    "beta1r must be a numeric vector (not a matrix)",
    arg = "beta1r"
  )
  assert_numeric_finite_values(beta1r, "beta1r")

  assert_bad_argument_ok(
    is.matrix(beta2r),
    "beta2r must be a matrix",
    arg = "beta2r"
  )
  assert_numeric_finite_values(beta2r, "beta2r")

  assert_bad_argument_ok(
    is.matrix(theta) || is.null(dim(theta)),
    "theta must be a numeric vector or a matrix",
    arg = "theta"
  )
  assert_numeric_finite_values(theta, "theta")

  p <- length(beta1r)
  assert_dimension_ok(
    p == ncol(beta2r),
    paste0(
      "length(beta1r) (", p, ") must equal ncol(beta2r) (",
      ncol(beta2r), ") -- the predictor axis"
    )
  )

  i_dim <- nrow(beta2r)
  theta_is_matrix <- is.matrix(theta)
  theta_i <- if (theta_is_matrix) nrow(theta) else length(theta)
  assert_dimension_ok(
    theta_i == i_dim,
    paste0(
      "the theta axis (", theta_i, ") must equal nrow(beta2r) (",
      i_dim, ") -- the system-component axis"
    )
  )

  if (!is.null(names(beta1r)) && !is.null(colnames(beta2r))) {
    assert_bad_argument_ok(
      identical(names(beta1r), colnames(beta2r)),
      "names(beta1r) must match colnames(beta2r) (the predictor axis)",
      arg = "beta2r"
    )
  }

  # beta1(theta) = beta1r - (beta2r)' theta ; crossprod(beta2r, theta) = t(beta2r) %*% theta
  out <- beta1r - crossprod(beta2r, theta)
  if (theta_is_matrix) {
    rownames(out) <- names(beta1r)
    colnames(out) <- colnames(theta)
    return(out)
  }
  out <- drop(out)
  names(out) <- names(beta1r)
  out
}
